### ISSUE TITLE
@typescript-eslint/naming-convention: add HTTP headers to ignorelist

### ISSUE THREAD

**Issue by jonahsnider** [xojs/eslint-config-xo-typescript#44]
![VS Code screenshot](https://user-images.githubusercontent.com/7608555/136217786-236a63d8-e86a-4f4a-86ce-5eeedb14b38c.png)

HTTP headers and other common words (ex. `POST` or `GET`) should be added to an ignorelist so the camelcase validator doesn't trigger for them.

**Comment by sindresorhus** [comment]
Does the rule have this ability?

**Comment by sindresorhus** [comment]
I don't think that's a good idea. It's messy and it will also make non-header properties with the same name not be linted.

**Comment by EdJoPaTo** [comment]
I think keys from other libraries should be allowed in general. Other libraries have their defined keys in options and so on and I cant those keys from this side.

Because of this I disabled this rule for most of my projects because two of my most used libraries have keys that are not written in the same way xo wants them to be. This results in hundreds of errors which made me prefer to just disable the rule at all. Which is sad as I like the idea of enforcing variable style.

**Comment by maxpain** [comment]
Any updates on this?
